# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "ohci_hcd" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/da4ce9b3-5bcd-477f-8d6d-899e0291747d";
      fsType = "ext4";
    };

  fileSystems."/media/sf_Dropbox" =
    { device = "Dropbox";
      fsType = "vboxsf";
    };

  fileSystems."/media/sf_Shared" =
    { device = "Shared";
      fsType = "vboxsf";
    };

  fileSystems."/media/sf_Thing" =
    { device = "Thing";
      fsType = "vboxsf";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/7b5b96a4-5e0a-40db-aa55-cd0a34d8629c"; }
    ];

  nix.maxJobs = lib.mkDefault 1;
  virtualisation.virtualbox.guest.enable = true;
}
