#!/bin/sh

NIX_PATH=

nix-build \
  -o systems-result \
  -I configuration=/etc/nixos/systems/elio.nix \
  -I nixpkgs=/etc/nixos/nixpkgs/ \
  -I nixos=/etc/nixos/nixos/ \
  release.nix \
  --show-trace
