#!/bin/sh

### Avoid uname -a prints the host nodename
#export SYSVER=$(uname -a)
export SYSVER=$(uname -smrvo)

function build () {
    nix-build \
	--show-trace \
	-I blcr="/var/run/current-system/sw/bin" \
	-A "hol_light_$1" \
	-o ~/bin/"hol_light_$1" \
	build_hol_light_contexts.nix
}

function die () {
    echo "Error building $1" 1>&2
    echo "Abort" 1>&2
    exit 1
}

for variant in core test algebra multivariate complex gcs card sosa hypercomplex
do
    build "${variant}" || die $variant
    echo "$variant built successfully"
done
