#!/bin/sh

export SYSVER=$(uname -a)
#export CURRENT_SYSTEM=$(readlink "/run/current-system")

function build () {
    nix-build \
	--show-trace \
	-I blcr="/var/run/current-system/sw/bin" \
	-A "hol_light_$1" \
	-o ~/bin/"hol_light_$1" \
	build_hol_light_contexts.nix
}

function die () {
    echo "Error building $1" 1>&2
    echo "Abort" 1>&2
    exit 1
}

for variant in core test multivariate complex full gcs card sosa hypercomplex
do
    build "${variant}" || die $variant
    echo "$variant built successfully"
done
