# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.kernelModules =
    [ "uhci_hcd" "ehci_hcd" "ehci_pci" "ata_piix"
      "firewire_ohci" "usb_storage"
    ];

  boot.initrd.availableKernelModules =
    [ "uhci_hcd" "ehci_hcd" "ehci_pci" "ata_piix"
      "firewire_ohci" "usb_storage" ];
  
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems = [ { mountPoint = "/"; label = "nixos"; } ];
  swapDevices = [ { label = "swap"; } ];


  nix.maxJobs = 4;

  # services.xserver.videoDrivers = [ "nvidia" ];
}
